#7793: Created migrate module from custom csv.
aster06/UrbanObserver pull request #47
Opened 2024-04-15 13:20 UTC by aster06

2024-04-15 14:08 UTC, faust174 commented on web/modules/custom/migration_csv/assets/users_registration.csv
> +uid,country,user_city
Probably custom user data should be in the same CSV file as default registration data or at least it should have the same uid's.

2024-04-15 14:08 UTC, faust174 approved these changes

2024-04-15 15:09 UTC, lavrenchuk-dev requested changes

2024-04-15 15:09 UTC, lavrenchuk-dev commented on web/modules/custom/migration_csv/src/Plugin/migrate/destination/CustomDestination.php
> +    MigrationInterface $migration = NULL): CustomDestination|ContainerFactoryPluginInterface|static {
?

2024-04-15 15:09 UTC, lavrenchuk-dev commented on web/modules/custom/migration_csv/migrations/migration_csv_users.yml
> +    default_value: article
article?

2024-04-15 15:09 UTC, lavrenchuk-dev commented on config/default/core.extension.yml
> +  phpass: 0
why do you need this?

2024-04-22 08:46 UTC, aster06 commented on config/default/core.extension.yml
> +  phpass: 0
Module Migrate Drupal requires this

2024-04-22 09:10 UTC, lavrenchuk-dev approved these changes

2024-04-22 09:10 UTC, merged