#7416: Created and styled components for header in storybook
aster06/UrbanObserver pull request #7
Opened 2024-02-20 17:31 UTC by aster06

2024-02-20 17:39 UTC, lavrenchuk-dev requested changes

2024-02-20 17:39 UTC, lavrenchuk-dev commented on web/themes/custom/urbanobserver/components/03-organisms/site/site-header/site-header.twig
> +{#    </div>#}
Commented code without explanation shouldn't be commited

2024-02-20 17:39 UTC, lavrenchuk-dev commented on web/themes/custom/urbanobserver/components/00-base/00-defaults/_01-variables.scss
> +@import url('https://fonts.googleapis.com/css2?family=Big+Shoulders+Inline+Text:wght@100..900&family=Big+Shoulders+Text:wght@100..900&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap');
Generally, assets like fonts are better to download and include from local files.
Not hard requirement but just FYI

2024-02-21 08:03 UTC, aster06 commented on web/themes/custom/urbanobserver/components/03-organisms/site/site-header/site-header.twig
> +{#    </div>#}
I think this part of commented code could be useful for me in the future because I'm just learning and these commented blocks and classes can help me in styling my header. If it's not, I'll delete it in the future commits.

2024-02-21 09:04 UTC, lavrenchuk-dev approved these changes

2024-02-21 09:04 UTC, merged